name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
      
      - name: Build website
        run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: testcafe/testcafe
    steps:
      - name: TestCafé
        run: testcafe chromium test/weeknumber.js

  # build-and-deploy:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: node:18
  #     env:
  #       NODE_ENV: development
  #     ports:
  #       - 80
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Setup Node.js environment
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '16'

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Build the application
  #       run: npm run build

  #     # - name: Run the application
  #     #   run: npm run dev

  #     - name: TestCafé
  #       uses: DevExpress/testcafe-action@latest
  #       with:
  #           args: "chrome test/weeknumber.js"

  #     # - name: Run TestCafe tests
  #     #   run: npx testcafe chrome tests/